org: jakobjavascript24
service: remember-my-application

useDotenv: true

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    external:
      - nodemailer

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  role: arn:aws:iam::136191772737:role/adminrole

  environment:
    # JWT_SECRET: ${env:JWT_SECRET}
    # SES_FROM_EMAIL: ${env:SES_FROM_EMAIL}
    JWT_SECRET: ${env:JWT_SECRET}
    SES_FROM_EMAIL: ${env:SES_FROM_EMAIL}
    GMAIL_USER: ${env:GMAIL_USER}
    GMAIL_APP_PASSWORD: ${env:GMAIL_APP_PASSWORD}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - http://myappliesbucket.s3-website.eu-north-1.amazonaws.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: false

functions:
  createUser:
    handler: functions/users/signup/index.handler
    events:
      - httpApi:
          path: /api/user/signup
          method: post

  login:
    handler: functions/users/login/index.handler
    events:
      - httpApi:
          path: /api/user/login
          method: post

  createApplication:
    handler: functions/applications/createApplication/index.handler
    events:
      - httpApi:
          path: /api/applications
          method: post

  deleteApplication:
    handler: functions/applications/deleteApplication/index.handler
    events:
      - httpApi:
          path: /api/applications/{id}
          method: delete

  updateApplication:
    handler: functions/applications/updateApplication/index.handler
    events:
      - httpApi:
          path: /api/applications/{id}
          method: patch

  readApplication:
    handler: functions/applications/readApplication/index.handler
    events:
      - httpApi:
          path: /api/applications
          method: get

  uploadUrl:
    handler: functions/applications/uploadUrl/index.handler
    events:
      - httpApi:
          path: /api/files/upload-url
          method: post

  postReview:
    handler: functions/review/postReview/index.handler
    events:
      - httpApi:
          path: /api/review
          method: post

  getReview:
    handler: functions/review/readReview/index.handler
    events:
      - httpApi:
          path: /api/review
          method: get

  checkReminders:
    handler: functions/reminder/reminder/index.handler
    events:
      - schedule:
          # rate: cron(0 8 * * ? *)
          rate: rate(1 minute)
          enabled: true

resources:
  Resources:
    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ApplicationsTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
